name: bugsnag_breadcrumbs_http
description: Bugsnag network breadcrumbs for https://pub.dev/packages/http
version: 4.0.0
homepage: https://www.bugsnag.com/
documentation: https://docs.bugsnag.com/platforms/flutter/
repository: https://github.com/bugsnag/bugsnag-flutter
issue_tracker: https://github.com/bugsnag/bugsnag-flutter/issues

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  bugsnag_flutter:
    path: ../bugsnag_flutter
  http: ">=0.13.4"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
